version: '3.8'

services:
  fraud_api:
    build: .
    container_name: fraud_api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./api:/app/api
      - ./config:/app/config
      - ./scripts:/app/scripts
      - ./security:/app/security
    depends_on:
      - duckdb
      - neo4j
    networks:
      - fraud_network

  duckdb:
    image: ubuntu
    container_name: duckdb
    command: ["sleep", "infinity"]
    volumes:
      - ./data/database:/app/database
    networks:
      - fraud_network

  neo4j:
    image: neo4j:4.4
    container_name: fraud_neo4j
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/database:/data
    networks:
      - fraud_network

networks:
  fraud_network:
    driver: bridge
